---
:exception_notification: false
:exception_notification_sender: Sender Name <nobody@localhost>
:exception_notification_receipients: nobody@localhost
:login_email: false
:branding_codename: salorhospitality
:branding_title: SalorHospitality
:use_safe_device_path: false