--- !map:ActiveSupport::HashWithIndifferentAccess 
name: BillGastro
subtitle: The innovative POS Software
address: www.billgastro.com
taxnumber: Tax Number
slogan1: The innovative POS Software
slogan2: Visit us at
internet: www.billgastro.com
email: office@billgastro.com
printer_kitchen: /dev/usblp1
printer_bar: /dev/billgastro-printer-back-top-left
printer_guestroom: /dev/usblp0
automatic_printing: "1"
