--- !map:ActiveSupport::HashWithIndifferentAccess 
name: BillGastro
subtitle: The innovative POS Software
address: Address
taxnumber: Tax Number
slogan1: Slogan 1
slogan2: Slogan 2
internet: Internet Address
email: Email Address
